# eureka:
#   client:
#     enabled: false # Отключаем Eureka при запуске не локально
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://registry:8761/eureka
