spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath

server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://registry:8761/eureka
