spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/account-service/**
        - id: bill-service
          uri: http://localhost:8082
          predicates:
            - Path=/bill-service/**
        - id: book-service
          uri: http://localhost:8083
          predicates:
            - Path=/book-service/**
springdoc:
  openapi-gateway:
    service-url:
      account-service: http://localhost:8081/v3/api-docs
      bill-service: http://localhost:8082/v3/api-docs
      book-service: http://localhost:8083/v3/api-docs

server:
  port: 8989
