spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # routes:
      #   - id: account-service
      #     uri: lb://account-service
      #     predicates:
      #       - Path=/account-service/**

      #   - id: bill-service
      #     uri: lb://bill-service
      #     predicates:
      #       - Path=/bill-service/**

server:
  port: 8989
