spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - RewritePath=/account-service(?<segment>/.*), $1
            - AddResponseHeader=X-Forwarded-Prefix, /account-service
        - id: bill-service
          uri: lb://bill-service
          predicates:
            - Path=/bill-service/**
          filters:
            - RewritePath=/bill-service(?<segment>/.*), $1
            - AddResponseHeader=X-Forwarded-Prefix, /bill-service
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
          filters:
            - RewritePath=/book-service(?<segment>/.*), $1
            - AddResponseHeader=X-Forwarded-Prefix, /book-service
        - id: swagger-ui-account
          uri: lb://account-service
          predicates:
            - Path=/account-service/swagger-ui.html, /account-service/swagger-ui/**, /account-service/v3/api-docs
          filters:
            - RewritePath=/account-service(?<segment>/.*), $1
        - id: swagger-ui-bill
          uri: lb://bill-service
          predicates:
            - Path=/bill-service/swagger-ui.html, /bill-service/swagger-ui/**, /bill-service/v3/api-docs
          filters:
            - RewritePath=/bill-service(?<segment>/.*), $1
        - id: swagger-ui-book
          uri: lb://book-service
          predicates:
            - Path=/book-service/swagger-ui.html, /book-service/swagger-ui/**, /book-service/v3/api-docs
          filters:
            - RewritePath=/book-service(?<segment>/.*), $1



server:
  port: 8989
