springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /account-service/v3/api-docs
        name: account-service
      - url: /bill-service/v3/api-docs
        name: bill-service
spring:
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates: 
            - Path=/v3/api-docs/**
          filters: 
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs


server:
  port: 8989
