spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${ACCOUNT_SERVICE_DATABASE_HOST:localhost}:5432/account_service_db
    username: qwerty
    password: qwerty
  liquibase:
    change-log: src/main/resources/db/changelog/db.changelog-master.xml

server:
  port: 8081
