spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${ACCOUNT_SERVICE_DATABASE_HOST:localhost}:5432/account_service_db
    username: qwerty
    password: qwerty

server:
  port: 8081

