spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${BILL_SERVICE_DATABASE_HOST:localhost}:5432/bill_service_db
    username: qwerty
    password: qwerty
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    
server:
  port: 8082
